FROM python:3.10-slim

WORKDIR /consumer
COPY requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY consumer.py ./consumer.py

ENTRYPOINT [ "python3", "consumer.py"]