version: '3.9'
services:
  producer:
    build: producer
    depends_on:
      - broker
    volumes:
      - ./twcs/twcs.csv:/producer/twcs.csv:ro

  broker:
    build: broker
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=keeper:2181    
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - keeper

  keeper:
    image: bitnami/zookeeper:3.7
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes